In [2]:
import numpy as np
import pandas as pd
# Burda elestik net fonksyonunu.
from sklearn.linear_model import Ridge, Lasso, ElasticNet
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split, cross_val_score
import matplotlib.pyplot as plt
# Elastiknet cv fonksyonunu import etme işlemlerini yapmaya çalışıyorum.
from sklearn.linear_model import RidgeCV, LassoCV, ElasticNetCV

In [4]:
# Veri setinin okunmasını sağlıyorum.
df = pd.read_csv(r"C:\Users\realb\Desktop\ML_dersler\ML_201\ElasticNet Regresyon Model\Hitters.csv")

# Veri setinin içinden eksik gözlemleri çıkarmak gerekiyor bu işlemi yapıyorum.
df = df.dropna()

# Şimdi ise dummies ile kukla veri işlemi yapıyorum. One end coding yöntemi ile bu işlemi yapıyorum.
dms = pd.get_dummies(df[['League', 'Division','NewLeague']])

# Bağımlı değişkenimi "y" atıyorum.
y = df["Salary"]

# Veri setimiz içindeki bağımlı değişkeni ve katogorik değişkenlerin götürülmesi işlemini yapıyorum.
X_ = df.drop(['Salary', 'League', 'Division', 'NewLeague'], axis=1).astype('float64')

# Sonuçunda yukardaki değerlerin dummi versyonlarını ve bağımsız değişkenlerimi bir arada tutma işlemini yapıyorum.
X = pd.concat([X_, dms[['League_N', 'Division_W', 'NewLeague_N']]], axis=1)

# Şimdi ise veri setimizde train ve test ayrımı yapmak için bu ayrımı yapma işlemini yapıyorum.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [5]:
# Şimdi model kurma işlemini gerçekleştiriyorum.
enet_model = ElasticNet().fit(X_train, y_train)

C:\Users\realb\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.488e+06, tolerance: 3.899e+03
  model = cd_fast.enet_coordinate_descent(


In [6]:
# Model içinden kat sayılara bakıyorum.
enet_model.coef_

array([ -1.86256172,   8.70489065,   5.10426375,  -2.89875799,
        -1.28642985,   5.24343682,   6.04480276,  -0.14701495,
        -0.21566628,  -0.7897201 ,   1.80813117,   0.80914508,
        -0.61262382,   0.26816203,   0.27172387,  -0.36530729,
        19.2186222 , -31.16586592,   8.98369938])

In [7]:
# Sabit teriminede erişebilirim. 
enet_model.intercept_

-6.465955602114036

In [9]:
# ŞİMDİ KURDUĞUM BU MODEL İLE BİR TAHMİN ETME İŞLEMİ GERÇEKLEŞTİRİYORUM.
# Bu tahmin işlemini train üzerinden gerçekleştiriyorum.
enet_model.predict(X_train)[0:10]

array([ 577.79111731,  617.33202224, 1031.39113156,  364.95861575,
        489.51894393,  300.74185842,  604.522666  ,  465.34678732,
        901.44473965,  703.20357123])

In [10]:
# Şimdi test veri setimiz üzerinden bu işlemi gerçekleştirebilirim.
enet_model.predict(X_test)[0:10]

array([ 577.79111731,  617.33202224, 1031.39113156,  364.95861575,
        489.51894393,  300.74185842,  604.522666  ,  465.34678732,
        901.44473965,  703.20357123])

In [12]:
# Şimdi bu tahmin edilen değerler üzerinden hatamı hesaplamaya çalışıyorum.
y_pred = enet_model.predict(X_test)
# Bu alandan hata kareler ortalamasını hesaplamaya çalışyorum.
np.sqrt(mean_squared_error(y_test, y_pred))

357.1676548181248

In [13]:
# R2 skorunu bu alandan hesaplamaya açalışıyorum.
r2_score(y_test, y_pred)

0.410702224693268

In [26]:
alphas = 10**np.linspace(10,-2,100)*0.5

In [29]:
# Tunned işlemi yapılacak olan model kurulumunu ayarlamaya çalışmaktayım. Ve bu modeli 10 kere kat katlı çarpımını alıp fit ediyorum.
enet_cv_model = ElasticNetCV(cv = 10).fit(X_train, y_train)


enet_cv_model_1 = ElasticNetCV(alphas = alphas, cv = 10).fit(X_train, y_train)

C:\Users\realb\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:614: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3249.948307124898, tolerance: 3241.4244490642723
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\realb\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:614: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 4337.003155091777, tolerance: 3241.4244490642723
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\realb\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:614: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 5751.4247870687395, tolerance: 3241.4244490642723
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\realb\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:614

C:\Users\realb\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:614: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 7127849.608623264, tolerance: 3582.448344789122
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\realb\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:614: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 7131404.055052064, tolerance: 3582.448344789122
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\realb\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:614: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 7134893.5765158, tolerance: 3582.448344789122
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\realb\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:614: Conv

In [30]:
# Şimdi yukarda ben cross validation işlemini yaptıuktan sonra bu işlem sonucunda optimum paremetreleri merak ediyorum ve bu alanda bir hesaplama yapmaya çalışıyorum.
enet_cv_model.alpha_

a1 = enet_cv_model_1.alpha_
print(a1)
# Optimum olarak bulmuş olduğu değeri bu alanda gözlemleyebilirim.

5748.784976988678


In [31]:
# Sabit değerini gözlemlemek istiyorum.
enet_cv_model.intercept_

i1 = enet_cv_model_1.intercept_
print(i1)
# Model sabit değerini bu alandan gözlemleyebilirim.

-31.46312122564109


In [32]:
# Kat sayılarımı gözlemlemek istersem.
enet_cv_model.coef_

enet_cv_model_1.coef_

array([ 0.61111381,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        , -0.        ,  0.        ,  0.11212622,  0.        ,
        0.25252702,  0.18656722,  0.00444355,  0.30988823,  0.        ,
       -0.        ,  0.        , -0.        ,  0.        ])

In [33]:
# Şimdi tunned edilmiş modelimizi fit etmiş bulunmaktayız.
enet_tunned = ElasticNet(alpha = enet_cv_model.alpha_).fit(X_train, y_train)

ebet_tunned_1 = ElasticNet(alpha = enet_cv_model_1.alpha_).fit(X_train, y_train)

In [34]:
y_pred = enet_tunned.predict(X_test)

y_pred_1 = enet_cv_model_1.predict(X_test)

In [42]:
# Şimdi bu final modelimizi kulanarak test veri setimiz için hatamızı hesaplanmasını yapalım.
h = np.sqrt(mean_squared_error(y_test, y_pred))
print(h)
# X bağımz değişkeni ve test veri seti üzerinden yapılna tahmin sonuçlarını hata oranını hesaplamasını yaptım.

np.sqrt(mean_squared_error(y_test, y_pred_1))

394.15280563218795


393.97530658505536

In [40]:
r = r2_score(y_test, y_pred)
print(r)

r1 = r2_score(y_test, y_pred_1)
print(r1)

0.2823382467773815
0.282984471251876


In [43]:
?ElasticNet
"""
Şimdi bu kod alanı çalıştırdığınızda alpha değeri 1 olarak görsebilir siniz.
l1_ratio ise 0.5 olarak default olarak degdiğini görebilirsiniz.
Bu argumanın değeri 0 olduğunda l2 cezalandırması
bu argumanın değeri 1 olduğunda ise l1 cezalandırılması yapılır.
Ynai 0-1 aralığında cezalandırma işlemi uygulamaları etkileri gözlenmiş olur.
Bu biz ikisinide etkilemisi için 0.5 olarak tanımlayarak bırakmış olduk.
Şİmdi bir önemli konu ise alpha değeri lambda değeri oranı etkilerken l1_ratio ise bu uygulamaların göreceli etkileri üzerinden bir işlem yapıyor.
Bu iki değişken üzerinden biribiri ilişki üzerinden isede optimum değeri bulunması yapılabilir.
Bu l1_ratio her değeri için farklı bir lambda ilede modele etkileri incelenebilmektedir.
Elestik net l1 ve l2 ayarlarını barındırması ve bunların ayarlanmasınbı bu alandan çalışması ve ayarlanması yapılmaktadır.
"""